added -ptest property to unit test action

diff --git a/.github/actions/unit-test/action.yml b/.github/actions/unit-test/action.yml
--- a/.github/actions/unit-test/action.yml
+++ b/.github/actions/unit-test/action.yml
@@ -7,9 +7,13 @@ runs:
   steps:
     - name: Run instrumentation unit tests
       id: run_tests
+      with:
+        java-version:
       shell: bash
       run: |
-        for attempt in {1..4}; do
-          echo "Attempt $attempt"
-          ./gradlew ${GRADLE_OPTIONS} --info test && break || (echo "Run instrumentation unit tests attempt $attempt failed, waiting 5 seconds..." && sleep 5)
+        for version in 8 11 17 20; do
+          for attempt in {1..4}; do
+            echo "Attempt $attempt"
+            ./gradlew ${GRADLE_OPTIONS} --info -Ptest${version} test && break || (echo "Run instrumentation unit tests attempt $attempt failed, waiting 5 seconds..." && sleep 5)
+          done
         done
